# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99889703e779a753bf54355a28db725da997d2966068afb26da4d8cb76c894b212e5c2afd3aa2dfda5640cdfb7ffdd31758529d653c223264c3044bfbac0c952

test:
  secret_key_base: fef4f42dc5aaa728c8c7bd4d997e6dba3b6c61a353b349894ab93e1229241807416e1aaa167e355c7a33d9e5cec74ec64a41ebd29d7e51044b54a1980f616b91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
